services:
  dewey:
    image: ghcr.io/djmehs17/dewey:latest
    container_name: dewey
    env_file:
      - .env
    ports:
      - "8686:8686"
    volumes:
      - ./config:/config
      - /data:/data
    restart: unless-stopped
